apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - configmap.yaml
  - secrets.yaml
  - hpa.yaml
  - pdb.yaml
  - networkpolicy.yaml
  - serviceaccount.yaml

namespace: tinyschoolhub

commonLabels:
  app.kubernetes.io/name: tiny-school-hub
  app.kubernetes.io/component: api

images:
  - name: tinyschoolhub/api
    newTag: latest
